# Generated by Django 3.2.13 on 2022-06-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=13)),
                ('contact_number', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='script',
            name='redeemed_counter',
        ),
        migrations.CreateModel(
            name='ScriptRedeems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_redeems', to='script.customer')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_redeems', to='script.script')),
            ],
        ),
    ]
