# Generated by Django 3.2.13 on 2022-06-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_auto_20220609_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='customer_id_number',
            field=models.CharField(default='1', max_length=13),
            preserve_default=False,
        ),
    ]
